### ISSUE TITLE
Error : Cannot read JBIG2 image: jbig2-imageio is not installed

### ISSUE THREAD

**Issue by kilanmundera** [acid1103/PDFInverter#9]
Hi,

I run into this error when I try to use the script.

My command is :

`java -jar PDFInverter.jar myPDF.pdf myPDF-dark-mode.pdf`

And the error : 

```
Page 6/36
Inverting image "X41"
StreamHandler finishing remaining 3 task(s).
StreamHandler finishing remaining 2 task(s).
StreamHandler finishing remaining 1 task(s).
StreamHandler activity finished. Writing changes.
Exception in thread "main" org.apache.pdfbox.filter.MissingImageReaderException: Cannot read JBIG2 image: jbig2-imageio is not installed
	at org.apache.pdfbox.filter.Filter.findImageReader(Filter.java:163)
	at org.apache.pdfbox.filter.JBIG2Filter.decode(JBIG2Filter.java:67)
	at org.apache.pdfbox.cos.COSInputStream.create(COSInputStream.java:80)
	at org.apache.pdfbox.cos.COSStream.createInputStream(COSStream.java:176)
	at org.apache.pdfbox.pdmodel.common.PDStream.createInputStream(PDStream.java:241)
	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.createInputStream(PDImageXObject.java:793)
	at org.apache.pdfbox.pdmodel.graphics.image.SampledImageReader.from1Bit(SampledImageReader.java:397)
	at org.apache.pdfbox.pdmodel.graphics.image.SampledImageReader.getRGBImage(SampledImageReader.java:212)
	at org.apache.pdfbox.pdmodel.graphics.image.SampledImageReader.getRGBImage(SampledImageReader.java:154)
	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getOpaqueImage(PDImageXObject.java:570)
	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getImage(PDImageXObject.java:494)
	at org.apache.pdfbox.pdmodel.graphics.image.PDImageXObject.getImage(PDImageXObject.java:460)
	at org.apache.pdfbox.contentstream.PDFColorInverter.invertImagesOnPage(PDFColorInverter.java:464)
	at org.apache.pdfbox.contentstream.PDFColorInverter.invert(PDFColorInverter.java:437)
	at org.abitoff.pdfinverter.Main.main(Main.java:89)
```

Here is the version of java : 
```
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12-Ubuntu-120.04)
OpenJDK 64-Bit Server VM (build 14.0.2+12-Ubuntu-120.04, mixed mode, sharing)
```

And I also have a question : 
I'd like to exclude the images from the invertion (I'd like to keep them original), but I dno't understand how to use the option.
Could you just give an option about how to use the option in the command ?

Thanks !

**Comment by acid1103** [comment]
Hi Charly, the simple answer here would be to run the command `java -jar PDFInverter.jar myPDF.pdf myPDF-dark-mode.pdf black false`
